
import type { Metadata } from 'next'


export const metadata: Metadata = {
    title: 'Search Page',
    description: 'Generated by Mohamed Elsayed',
}

const Search = () => {
    return (
        <h1>Search Page </h1>
    )
}

export default Search